/*
Project Name: Steal and Escape: A 3D top-down semi-escape stealth game developed in Unreal Engine
Course: CSCI 491 Seminar
Template Used: Unreal Engine 4 TopDown C++ Template (Epic Games)
Original Template Author: Epic Games

File Name: StealAndEscapeCharacter.cpp
Modified By: Kushal Poudel and Alok Poudel 
Last Modified: March 1, 2026

Description: This is a character class which is autogenerated form Unreal Engine
C++ Template (TopDown). The components such as camera setup, cursor decal logic, and click-to-move
components are template-generated. We Addeded different custom features here based on our project

Custom gameplay features which are added are:
1.) WASD keyboard movement
2.) Sprint functionality while pressing Shift key
3.) Grab animation triggered by G key (which is an Animation Montage)
4.) Adjustable WalkSpeed and RunSpeed variables
*/
#include "StealAndEscapeCharacter.h"
#include "UObject/ConstructorHelpers.h"
#include "Camera/CameraComponent.h"
#include "Components/DecalComponent.h"
#include "Components/CapsuleComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/PlayerController.h"
#include "GameFramework/SpringArmComponent.h"
#include "HeadMountedDisplayFunctionLibrary.h"
#include "Materials/Material.h"
#include "Engine/World.h"
#include "GameFramework/Controller.h"

AStealAndEscapeCharacter::AStealAndEscapeCharacter()
{
	
	GetCapsuleComponent()->InitCapsuleSize(42.f, 96.0f);
	bUseControllerRotationPitch = false;
	bUseControllerRotationYaw = false;
	bUseControllerRotationRoll = false;

	GetCharacterMovement()->bOrientRotationToMovement = true;
	GetCharacterMovement()->RotationRate = FRotator(0.f, 640.f, 0.f);
	GetCharacterMovement()->bConstrainToPlane = true;
	GetCharacterMovement()->bSnapToPlaneAtStart = true;

	// Setting initial walkinh speed using walkspeed variable - Modified by Alok
	GetCharacterMovement()->MaxWalkSpeed = WalkSpeed;

	// Create camera boom
	CameraBoom = CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));
	CameraBoom->SetupAttachment(RootComponent);
	CameraBoom->SetUsingAbsoluteRotation(true);
	CameraBoom->TargetArmLength = 800.f;
	CameraBoom->SetRelativeRotation(FRotator(-60.f, 0.f, 0.f));
	CameraBoom->bDoCollisionTest = false;

	// Create camera
	TopDownCameraComponent = CreateDefaultSubobject<UCameraComponent>(TEXT("TopDownCamera"));
	TopDownCameraComponent->SetupAttachment(CameraBoom, USpringArmComponent::SocketName);
	TopDownCameraComponent->bUsePawnControlRotation = false;

	// Create cursor decal
	CursorToWorld = CreateDefaultSubobject<UDecalComponent>("CursorToWorld");
	CursorToWorld->SetupAttachment(RootComponent);

	static ConstructorHelpers::FObjectFinder<UMaterial> DecalMaterialAsset(TEXT("Material'/Game/TopDownCPP/Blueprints/M_Cursor_Decal.M_Cursor_Decal'"));
	if (DecalMaterialAsset.Succeeded())
	{
		CursorToWorld->SetDecalMaterial(DecalMaterialAsset.Object);
	}

	CursorToWorld->DecalSize = FVector(16.0f, 32.0f, 32.0f);
	CursorToWorld->SetRelativeRotation(FRotator(90.0f, 0.0f, 0.0f).Quaternion());

	PrimaryActorTick.bCanEverTick = true;
}

/*Overiding Unreal Engine Method to add custom input binding 
  necessary for WASD Movement as well as spint and grab item feature
*/
void AStealAndEscapeCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	PlayerInputComponent->BindAxis("MoveForward", this, &AStealAndEscapeCharacter::MoveForward);
	PlayerInputComponent->BindAxis("MoveRight", this, &AStealAndEscapeCharacter::MoveRight);

	// Shift for runing - Added by Alok
	PlayerInputComponent->BindAction("Run", IE_Pressed, this, &AStealAndEscapeCharacter::StartRun);
	PlayerInputComponent->BindAction("Run", IE_Released, this, &AStealAndEscapeCharacter::StopRun);

	//G for grab item- Added by  Kushal 
	PlayerInputComponent->BindAction("Grab", IE_Pressed, this, &AStealAndEscapeCharacter::GrabPressed);
}
/* Custom Method for forward movement with W key as well as Backward movement with S key 
   Movement direction is being calculated  in relation with conteollers yaw rotation 
   Character moves depending upon the direcction where the camrea is faced-- Alok
*/
void AStealAndEscapeCharacter::MoveForward(float Value)
{
	if (Controller && Value != 0.0f)
	{
		const FRotator Rotation = Controller->GetControlRotation();
		const FRotator YawRotation(0, Rotation.Yaw, 0);

		const FVector Direction = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::X);
		AddMovementInput(Direction, Value);
	}
}

// Custom Method for Right movement with D key as well as Left movement with A key-- Alok
void AStealAndEscapeCharacter::MoveRight(float Value)
{
	if (Controller && Value != 0.0f)
	{
		const FRotator Rotation = Controller->GetControlRotation();
		const FRotator YawRotation(0, Rotation.Yaw, 0);

		const FVector Direction = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::Y);
		AddMovementInput(Direction, Value);
	}
}

/* Custom Methods for Sprint functionality using Shift key
   When Shift key is pressed character speed is increased to  matchRunSpeed
   and when released character speed is returned back to WalkSpeed -- Alok
*/
void AStealAndEscapeCharacter::StartRun()
{
	GetCharacterMovement()->MaxWalkSpeed = RunSpeed;
}

void AStealAndEscapeCharacter::StopRun()
{
	GetCharacterMovement()->MaxWalkSpeed = WalkSpeed;
}

/* Custom Method for Grab functionality using G key
   When G key is pressed character plays Grab animation montage
   For error checking Method first checks whether GrabMontage, Mesh and Animation Instance are valid
   Animation will not restart if it is already playing -- Added by Kushal
*/
void AStealAndEscapeCharacter::GrabPressed()
{
	// G will play animation montage for garb 
	if (!GrabMontage)
	{
		return;
	}

	if (!GetMesh())
	{
		return;
	}

	UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance();
	if (!AnimInstance)
	{
		return;
	}

	//not to restart if already playing
	if (!AnimInstance->Montage_IsPlaying(GrabMontage))
	{
		PlayAnimMontage(GrabMontage);
	}
}

//Unreal Engine TopDown C++ template method
void AStealAndEscapeCharacter::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	if (CursorToWorld != nullptr)
	{
		if (APlayerController* PC = Cast<APlayerController>(GetController()))
		{
			FHitResult TraceHitResult;
			PC->GetHitResultUnderCursor(ECC_Visibility, true, TraceHitResult);

			FVector CursorFV = TraceHitResult.ImpactNormal;
			FRotator CursorR = CursorFV.Rotation();

			CursorToWorld->SetWorldLocation(TraceHitResult.Location);
			CursorToWorld->SetWorldRotation(CursorR);
		}
	}
}